name = "multiwfs"
uuid = "cda67f0e-380f-4251-b495-3ffd3b0a3939"
authors = ["aditya-sengupta <adityars@ucsc.edu>"]
version = "0.1.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
